PLAT-3006 Add unbound policy test to opentdf/tests
opentdf/tests pull request #139
Opened 2024-02-12 14:48 UTC by mustyantsev

2024-02-12 15:00 UTC, sievdokymov-virtru reviewed
@mustyantsev think need to add this test into CI test scope

2024-02-12 17:05 UTC, dmihalcik-virtru requested changes

2024-02-12 17:05 UTC, dmihalcik-virtru commented on xtest/sdk/py/test_unbound_policy.py
> +
```suggestion
        client.decrypt_file(sampleTdfStorage, os.path.join(cwd, "sample_policy.txt"))
        log.error("Broken policy ignored")
        sys.exit(1)
```

2024-02-12 17:05 UTC, dmihalcik-virtru commented on xtest/sdk/py/test_unbound_policy.py
> +    try:
Move this `try` down to the decrypt_file line below

2024-02-12 17:05 UTC, dmihalcik-virtru commented on xtest/sdk/py/test_unbound_policy.py
> +        error_message = f"An error occurred: {e}"
Add a validation here that this exception has an expected message. I don't know what that might be, and raise if not

2024-02-12 17:05 UTC, dmihalcik-virtru commented on xtest/sdk/py/test_unbound_policy.py
> +        updated_tdf_file = "updated_file.tdf"
You might want to add some more logging to support better debugging of the CI log files

2024-02-12 21:01 UTC, dmihalcik-virtru requested changes

2024-02-12 21:01 UTC, dmihalcik-virtru commented on xtest/sdk/py/test_unbound_policy.py
> +        client.decrypt_file(sampleTdfStorage, os.path.join(cwd, "sample_policy.txt"))
```suggestion
        client.decrypt_file(sampleTdfStorage, os.path.join(cwd, "sample_policy.txt"))
        log.error("Broken policy ignored")
        sys.exit(1)
```

2024-02-13 18:02 UTC, patmantru submitted a review, later dismissed

2024-02-14 16:57 UTC, dmihalcik-virtru requested changes

2024-02-14 16:57 UTC, dmihalcik-virtru commented on xtest/sdk/py/test_unbound_policy.py
> +        sys.exit(0)
```suggestion
        assert False, "Broken policy should raise exception on attempt to decrypt"
```

You'll need some kind of check to see that the file with a broken policy was *not* decrypted, e.g. make sure it is not present in the output. You can raise an error here, for example, or check the output file does not exist

2024-02-21 14:58 UTC, dmihalcik-virtru approved these changes

2024-02-21 14:58 UTC, dmihalcik-virtru approved these changes

2024-02-21 14:58 UTC, dmihalcik-virtru commented on xtest/sdk/py/test_unbound_policy.py
> +            sys.exit(0)
To me this indicates an error in the SDK. It should raise an exception. When does this happen?

2024-02-21 15:40 UTC, merged